# Generated by Django 5.2.5 on 2025-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_offer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
